export const brandList = [
    {
      id: 0,
      imgSrc: "/logo_audi_dark.svg",
      title: "Audi",
      width: 100,
      height: 80,
      href: null
    },
  
    {
      id: 1,
      imgSrc: "/logo_bp_dark.png",
      title: "BP",
      width: 230,
      height: 60,
      href: null,
    },
  
    {
      id: 2,
      imgSrc: "/logo_ceiik_dark.webp",
      title: "CEIIK",
      width: 100,
      height: 80,
      href: null,
    },
    {
      id: 3,
      imgSrc: "/logo_csm_dark.webp",
      title: "CSM",
      width: 62,
      height: 110,
      href: null,
    },
    {
      id: 4,
      imgSrc: "/logo_gck_dark.webp",
      title: "GCK",
      width: 90,
      height: 90,
      href: null,
    },
    {
      id: 5,
      imgSrc: "/logo_gp_tychy_dark.svg",
      title: "GP Tychy",
      width: 180,
      height: 50,
      href: null,
    },
    {
      id: 6,
      imgSrc: "/logo_hl_dark.svg",
      title: "HL",
      width: 225,
      height: 35,
      href: null,
    },
    {
      id: 7,
      imgSrc: "/logo_kul_dark.svg",
      title: "KUL",
      width: 205,
      height: 50,
      href: null,
    },
    {
      id: 8,
      imgSrc: "/logo_mpit_dark.webp",
      title: "MPIT",
      width: 160,
      height: 120,
      href: null,
    },
    {
      id: 9,
      imgSrc: "/logo_primulator_dark.webp",
      title: "Primulator",
      width: 240,
      height: 40,
      href: null,
    },
    {
      id: 10,
      imgSrc: "/logo_rpekit_dark.webp",
      title: "RPEKIT",
      width: 135,
      height: 60,
      href: null,
    },
    {
      id: 11,
      imgSrc: "/logo_tmg_dark.svg",
      title: "TMG",
      width: 300,
      height: 60,
      href: null,
    },
    {
      id: 12,
      imgSrc: "/logo_ug_dark.svg",
      title: "UG",
      width: 140,
      height: 140,
      href: null,
    },
    {
      id: 13,
      imgSrc: "/logo_wfdif_dark.png",
      title: "WFDIF",
      width: 90,
      height: 90,
      href: null,
    }
];